project:
  type: website
  output-dir: ./docs

website:
  title: "Shravika Mittal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - fun.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



